[package]
name = "wireguard-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
# gtk = { version = "0.9.0", package = "gtk4", features = ["v4_14"] }
relm4 = "0.8.0"
relm4-components = "0.8.0"
tokio = { version = "1.38.1", features = ["full"] }
